---
- name: Ensure latest '{{ grafana_package_name }}' package is installed
  ansible.builtin.package:
    name: "{{ grafana_package_name }}"
    state: 'latest'

- name: Create Grafana configuration from template
  ansible.builtin.template:
    src: 'grafana/grafana.ini.j2'
    dest: '/etc/grafana/grafana.ini'
    owner: 'root'
    group: 'root'
    mode: '444'

- name: Enable and start '{{ grafana_service_name }}' service
  ansible.builtin.service:
    name: "{{ grafana_service_name }}"
    enabled: yes
    state: 'started'

- name: Install or update Grafana plugins
  community.grafana.grafana_plugin:
    name: "{{ item }}"
    version: 'latest'
    state: 'present'
  loop: '{{ grafana_plugins }}'
  register: grafana_plugins_state

- name: Setup Grafana data sources
  grafana.grafana.datasource:
    dataSource: '{{ item }}'
    grafana_api_key: '{{ grafana_api_key }}'
    grafana_url: '{{ grafana_url }}'
    state: 'present'
  loop: '{{ grafana_datasources }}'
  register: grafana_datasources_present_state

- name: 'Create static web root'
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '755'
  with_items:
    - '/var/www'
    - '/var/www/{{ ansible_facts["fqdn"] }}'

- name: 'Create external image storage directories'
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'nginx'
    group: 'root'
    mode: '755'
  with_items:
    - '/var/www/{{ ansible_facts["fqdn"] }}/share'
    - '/var/www/{{ ansible_facts["fqdn"] }}/upload'

- name: 'Enable SELinux booleans for Grafana reverse proxy backend connectivity'
  ansible.posix.seboolean:
    name: '{{ item }}'
    state: true
    persistent: true
  with_items:
    - 'httpd_can_network_connect'
    - 'httpd_can_network_connect_db'

- name: Restart Grafana
  ansible.builtin.service:
    name: "{{ grafana_service_name }}"
    state: 'restarted'
  when:
    - grafana_plugins_state is changed
    - grafana_datasources_present_state is changed
