---
# The package name of the node_exporter daemon.
prometheus_node_exporter_package_name: 'node-exporter'

# The service name of the node_exporter daemon (without '.service').
prometheus_node_exporter_service_name: 'prometheus-node-exporter'

# The environment file name of the node_exporter daemon.
prometheus_node_exporter_environment_file: 'prometheus-node-exporter'
