---
- name: Ensure infping packages are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - fping
    - influxdb

- name: Copy Infping binary
  ansible.builtin.file:
    src: infping/infping
    dest: /usr/local/bin/infping
    owner: root
    group: root
    mode: '555'
  register: infping_bin_state

- name: Copy Infping configuration
  ansible.builtin.template:
    src: infping/config.toml.j2
    dest: /etc/infping/infping.toml
    owner: root
    group: root
    mode: '444'
  register: infping_config_state

- name: Install Infping service (TODO; and TODO SystemD Reload)
  ansible.builtin.file:
    src: infping/infping.service
    dest: /etc/systemd/system/infping.service
    owner: root
    group: root
    mode: '444'
  register: infping_service_file_state

- name: Restart Infping service
  ansible.builtin.service:
    name: infping
    state: restarted
  when:
    - infping_bin_state is changed
    - infping_config_state is changed
