---
base_packages:
  default:
    - curl
    - git
    - wget
  almalinux:
    - bind-utils
    - bzip2
    - curl
    - firewalld
    - git
    - gzip
    - htop
    - mtr
    - net-tools
    - nmap-ncat
    - ssmtp
    - tar
    - tmux
    - traceroute
    - unzip
    - vim-enhanced
    - wget
    - whois
    - zip
  centos:
    - bind-utils
    - bzip2
    - curl
    - firewalld
    - git
    - gzip
    - htop
    - mtr
    - net-tools
    - nmap-ncat
    - ssmtp
    - tar
    - tmux
    - traceroute
    - unzip
    - vim-enhanced
    - wget
    - whois
    - zip
  fedora:
    - bind-utils
    - bzip2
    - curl
    - firewalld
    - git
    - gzip
    - htop
    - mtr
    - net-tools
    - nmap-ncat
    - ssmtp
    - tar
    - tmux
    - traceroute
    - unzip
    - vim-enhanced
    - wget
    - whois
    - zip
  redhat:
    - bind-utils
    - bzip2
    - curl
    - firewalld
    - git
    - gzip
    - htop
    - mtr
    - net-tools
    - nmap-ncat
    - ssmtp
    - tar
    - tmux
    - traceroute
    - unzip
    - vim-enhanced
    - wget
    - whois
    - zip
  rocky:
    - bind-utils
    - bzip2
    - curl
    - firewalld
    - git
    - gzip
    - htop
    - mtr
    - net-tools
    - nmap-ncat
    - ssmtp
    - tar
    - tmux
    - traceroute
    - unzip
    - vim-enhanced
    - wget
    - whois
    - zip

base_ssmtp_config_path: '/etc/ssmtp/ssmtp.conf'
base_ssmtp_host: 'localhost:25'
base_ssmtp_password: ''
base_ssmtp_rewritedomain: "{{ ansible_facts['fqdn'] }}"
base_ssmtp_username: ''
