---
nginx_setup: 'upgrade'
nginx_manage_repo: false
nginx_install_from: 'os_repository'
nginx_branch: 'stable'

nginx_config_main_template:
  config:
    main:
      pcre_jit: true

nginx_config_http_template_enable: true
nginx_config_http_template:
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/grafana.conf
    backup: true
    config:
      map:
        mappings:
          - string: '$http_upgrade'
            variable: '$connection_upgrade'
            content:
              - value: default
                new_value: 'upgrade'
              - value: '""'
                new_value: 'close'
      upstreams:
        - name: 'grafana'
          servers:
            - address: '127.0.0.1:3000'
      servers:
        - core:
            listen:
              - address: '*'
                port: 80
                default_server: true
                reuseport: true
              - address: '[::]'
                port: 80
                default_server: true
                reuseport: true
            server_name: '{{ ansible_facts["fqdn"] }}'
            client_max_body_size: '50m'
            tcp_nodelay: true
          locations:
            - location: '= /robots.txt'
              core:
                types: [{mime: 'text/plain', extensions: 'txt'}]
                default_type: '"text/plain;charset=utf-8"'
              rewrite:
                return:
                  code: 200
                  text: '"User-agent: *\nDisallow: /\n"'
            - location: '/share/'
              core:
                root: '/var/www/{{ ansible_facts["fqdn"] }}'
                client_body_temp_path: '/var/www/{{ ansible_facts["fqdn"] }}/upload'
                dav_methods: ['PUT', 'DELETE', 'MKCOL', 'COPY', 'MOVE']
                create_full_put_path: true
                dav_access: ['group:rw', 'all:r']
                limit_except:
                  method: ['GET', 'HEAD']
                  directive:
                    - 'allow 127.0.0.0/8'
                    - 'deny all'
            - location: '/'
              proxy:
                http_version: '1.1'
                set_header:
                  - field: 'Connection'
                    value: '$connection_upgrade'
                  - field: 'Host'
                    value: '$http_host'
                  - field: 'X-Forwarded-For'
                    value: '$proxy_add_x_forwarded_for'
                  - field: 'X-Forwarded-Host'
                    value: '$host'
                  - field: 'X-Forwarded-Proto'
                    value: '$scheme'
                  - field: 'X-Forwarded-Server'
                    value: '$host'
                  - field: 'X-Forwarded-Ssl'
                    value: '$https'
                  - field: 'X-Real-IP'
                    value: '$remote_addr'
                pass: 'http://grafana'
            - location: '/api/live'
              proxy:
                http_version: '1.1'
                set_header:
                  - field: 'Connection'
                    value: '$connection_upgrade'
                  - field: 'Host'
                    value: '$http_host'
                  - field: 'Upgrade'
                    value: '$http_upgrade'
                  - field: 'X-Forwarded-For'
                    value: '$proxy_add_x_forwarded_for'
                  - field: 'X-Forwarded-Host'
                    value: '$host'
                  - field: 'X-Forwarded-Proto'
                    value: '$scheme'
                  - field: 'X-Forwarded-Server'
                    value: '$host'
                  - field: 'X-Forwarded-Ssl'
                    value: '$https'
                  - field: 'X-Real-IP'
                    value: '$remote_addr'
                pass: 'http://grafana'
