---
- name: 'Ensure Jenkins repository is present'
  ansible.builtin.template:
    src: 'jenkins/jenkins.repo.j2'
    dest: "/etc/yum.repos.d/{{ jenkins_repo_file_name }}.repo"
    owner: 'root'
    group: 'root'
    mode: '444'

- name: 'Ensure packages are installed'
  ansible.builtin.package:
    name: "{{ jenkins_packages }}"
    state: 'present'

- name: 'Copy {{ jenkins_environment_file }} service environment configuration'
  ansible.builtin.template:
    src: 'jenkins/jenkins.env.j2'
    dest: "/etc/sysconfig/{{ jenkins_environment_file }}"
    owner: 'root'
    group: 'root'
    mode: '444'
  register: jenkins_environment_config_state

- name: 'Reload SystemD Daemon'
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: jenkins_environment_config_state is changed

# TODO

- name: 'Copy Jenkins firewalld service definition'
  ansible.builtin.template:
    src: 'firewalld/jenkins_service.xml.j2'
    dest: "/etc/firewalld/services/{{ jenkins_service_firewalld }}.xml"
    owner: 'root'
    group: 'root'
    mode: '444'
  register: jenkins_service_firewalld_state

- name: 'Reload firewalld'
  ansible.builtin.service:
    name: 'firewalld'
    state: 'reloaded'
  when: jenkins_service_firewalld_state is changed

- name: 'Permit traffic in default firewalld zone for Jenkins service'
  ansible.posix.firewalld:
    service: "{{ jenkins_service_firewalld }}"
    permanent: true
    state: 'enabled'

- name: 'Enable and start Jenkins service'
  ansible.builtin.systemd_service:
    name: "{{ jenkins_service_systemd }}"
    enabled: true
    state: 'started'
