---
- name: Ensure Prometheus packages are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - golang-github-prometheus
    - golang-github-prometheus-alertmanager

- name: Copy Prometheus configuration
  ansible.builtin.template:
    src: prometheus/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '444'
  register: prometheus_config_state

- name: Copy Prometheus Alertmanager configuration
  ansible.builtin.template:
    src: prometheus/alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml
    owner: root
    group: root
    mode: '444'
  register: prometheus_alertmanager_config_state

- name: Restart Prometheus service
  ansible.builtin.service:
    name: prometheus
    state: restarted
  when: prometheus_config_state is changed

- name: Restart Prometheus Alertmanager service
  ansible.builtin.service:
    name: prometheus-alertmanager
    state: restarted
  when: prometheus_alertmanager_config_state is changed

- name: Remove Cockpit Web Service package (conflicts with Prometheus port 9090)
  ansible.builtin.package:
    name: 'cockpit-ws'
    state: absent
  when: prometheus_port == 9090

- name: Enable and start Prometheus services
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: yes
    state: started
  with_items:
    - prometheus
    - prometheus-alertmanager
