---
# The system package name for Grafana.
grafana_package_name: 'grafana'

# The service unit name for Grafana.
grafana_service_name: 'grafana-server'

# The TCP port that Grafana will listen on.
grafana_port: 3000

# The url to the Grafana instance.
grafana_url: 'http://localhost:3000/'

# Grafana plugins to install and keep updated.
grafana_plugins:
- 'cloudflare-app'
- 'grafana-clock-panel'
- 'grafana-github-datasource'
- 'grafana-gitlab-datasource'
- 'grafana-image-renderer'
- 'grafana-simple-json-datasource'
- 'grafana-worldmap-panel'

# The service account user to use with Grafana API.
grafana_sa_user: 'ansible'

# The service account API token that acts as the password.
grafana_sa_password: ''
