---
- name: Ping All Hosts
  ansible.builtin.ping:

- name: Install '{{ ansible_distribution | lower }}' base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_packages[ansible_distribution | lower] | default(base_packages['default']) }}"

- name: Copy ssmtp config '{{ base_ssmtp_config_path }}'
  ansible.builtin.template:
    src: ssmtp/ssmtp.conf.j2
    dest: '{{ base_ssmtp_config_path }}'
    owner: root
    group: mail
    mode: '440'

- name: Copy 'root' user home directory files
  ansible.builtin.copy:
    src: 'skel.d/{{ item }}'
    dest: '/root/{{ item }}'
    owner: root
    group: root
    mode: '644'
    directory_mode: '755'
    backup: true
  with_items:
  - .tmux.conf
  - .vim/colors
  - .vim/colors/molokai.vim
  - .vimrc
